Notes taken from:

Learning Path: Deep Dive into Python Machine Learning, presented by Eder Santana, Chapter 4

by Ankita Thakur - Curator

Published by Packt Publishing, 2016

Learn what is Deep Learning, using Backpropagation with Theano

In [3]:
# Theano is a python library that lets you make mathematical calculations for multi-dimensional arrays
import theano
from theano import tensor as T, function

import numpy as np

## Function Definitions

In [15]:
X = T.matrix('x') # define a symbolic variable
Y = X ** 2 # Define the function 

Z = T.grad(Y.sum(), X) # Z is the derivative of y with respect to x (T.grad calculates the derivative)

F = function([X], [Y, Z])  # compile the symbolic graph

In [16]:
x = np.ones((2, 2)) * 3 # generate numpy array

# pass value to compiled function that moves numpy array to a specific position in memory to
# calculate the compiled graph
y, z = F(x)  

# We are moving variables from different positions in memory. 
# Shared variables concept in Theano useful for GPUs.
# You can move data beforehand to memory and leave it there.
# Won't need to consume GPU bandwidth by moving values back and forth.

## Print results

In [17]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)

[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 9.  9.]
 [ 9.  9.]]
------------
[[ 6.  6.]
 [ 6.  6.]]
